"""empty message

Revision ID: e1cbcaaaf046
Revises: dd478f55b31a
Create Date: 2019-03-13 18:34:21.701563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cbcaaaf046'
down_revision = 'dd478f55b31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.add_column(sa.Column('username', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=45), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=45), nullable=True))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
